http-listen-host: "0.0.0.0"
http-listen-port: 9000
http-host-allowlist: "*"

metrics-enabled: true
metrics-host: "0.0.0.0"
metrics-port: 9001
metrics-host-allowlist: "*"

# eth2 subcommand options

eth2.network: "/var/config/network-config.yaml"
# keys will be imported in keystore path which should be mounted to the container
eth2.keystores-path: "/etc/keys"
eth2.keystores-passwords-path: "/etc/passwords"

# key manager API options
eth2.key-manager-api-enabled: true

# slashing protection options
eth2.slashing-protection-enabled: true
eth2.slashing-protection-db-username: postgres
eth2.slashing-protection-db-password: postgres
eth2.slashing-protection-db-url: "jdbc:postgresql://db/web3signer"

