genesis-file="/var/lib/besu/execution-genesis.json"
data-path="/data"
network-id=7882
rpc-http-enabled=true
rpc-http-api=["ADMIN","ETH","NET","DEBUG","TXPOOL"]
host-allowlist=["*"]
rpc-http-cors-origins=["*"]
rpc-http-port=8545

rpc-ws-enabled=true
rpc-ws-api=["ADMIN","ETH","NET","DEBUG","TXPOOL"]
rpc-ws-port=8546

p2p-port=30308
miner-enabled=false
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
metrics-enabled=true
metrics-host="0.0.0.0"
p2p-enabled=false
node-private-key-file="/etc/besu/besu.key"
engine-rpc-enabled=true
engine-jwt-secret="/etc/besu/jwtsecret.txt"
engine-jwt-disabled=true
data-storage-format="BONSAI"
